
services:
  
  logstash:
    build:
      context: ./logstash  # Path to the directory containing the Logstash Dockerfile
      dockerfile: Dockerfile  # Path to the Logstash Dockerfile if named differently
    hostname: logstash-node
    ports:
      - "5044:5044"  # Expose Logstash Beats input port
      - "127.0.0.1:9600:9600"  # Expose Logstash HTTP API port
    networks:
      - logstash-network
    volumes:
      - ./logstash/velopipe:/usr/share/logstash/pipelines

  filebeat:
    build:
      context: ./filebeat  # Path to the directory containing the Filebeat Dockerfile
      dockerfile: Dockerfile  # Path to the Filebeat Dockerfile if named differently
    hostname: filebeat-node
    volumes:
      - ./input:/usr/share/filebeat/logs/velociraptor  # Adjust this path to your log files

    environment:
      - FILEBEAT_LOG_LEVEL=debug  # Optional: Adjust logging level if needed
    networks:
      - logstash-network
    depends_on:
      - logstash

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx2g -Xms2g  # Adjust memory limits as needed
      - ELASTIC_PASSWORD=elastic  # Set a password for the elastic user
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/esdata:/usr/share/elasticsearch/data
      - ./elastic/init-scripts:/usr/share/elasticsearch/config/scripts  # Mount init scripts
    networks:
      - logstash-network
    restart: unless-stopped

volumes:
  esdata:
    driver: local    

networks:
  logstash-network:
    driver: bridge